//
// Created by dingj on 8/8/2026.
//

#ifndef WHITEBOARD_PIPELINE_STAGE1_OBSERVEANDUI_CPP_H
#define WHITEBOARD_PIPELINE_STAGE1_OBSERVEANDUI_CPP_H

#endif //WHITEBOARD_PIPELINE_STAGE1_OBSERVEANDUI_CPP_H
